In [1]:
from pyspark.sql.types import *

Starting Spark application

SparkContext available as 'sc'.
HiveContext available as 'sqlContext'.

In [2]:
csv = sc.textFile(
'wasb:///HdiSamples/HdiSamples/SensorSampleData/building/building.csv'
)

In [3]:
data = csv.map(lambda s: s.split(",")).filter(lambda s: s[0] != "BuildingID").map(lambda s:(int(s[0]), int(s[2]), str(s[3]) ))

In [4]:
schma = StructType([
StructField("BuildingID", IntegerType(), False),
StructField("BuildingAge", IntegerType(), False),
StructField("HVACProduct", StringType(), False)
])

In [5]:
df = sqlContext.createDataFrame(data,schma)
df.registerTempTable("tmpBuilding")

In [6]:
buildings = sqlContext.sql("""SELECT * FROM tmpBuilding
WHERE BuildingAge < 20""")
buildings.show()

+----------+-----------+-----------+
|BuildingID|BuildingAge|HVACProduct|
+----------+-----------+-----------+
|         4|         17|     GG1919|
|         5|          3|    ACMAX22|
|         6|          9|     AC1000|
|         7|         13|     FN39TG|
|         9|         11|     GG1919|
|        11|         14|     AC1000|
|        14|         17|     GG1919|
|        15|         19|    ACMAX22|
|        17|         11|     FN39TG|
|        19|         14|     GG1919|
|        20|         19|    ACMAX22|
+----------+-----------+-----------+